myStr = "Andrés"
print("My name is " + myStr)
print(f"My name is {myStr}")
#print(dir(myStr))

# print(myStr.lower())
# print(myStr.upper())
# print(myStr.swapcase())
# print(myStr.capitalize())
# print(myStr.replace('Hello', 'hola'))
# print(myStr.replace('Hello', 'hola').upper())
# print(myStr.count('l'))
# print(myStr.startswith('bye'))
# print(myStr.split())
# print(myStr.find('W'))
# print(len(myStr))
# print(myStr.index('d'))
